name: Build & Test
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: 01 13 * * SAT
jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        method:
          - npm
          - npm-ct
          - pnpm
          - pnpm-ct
        deps:
          - with-deps
          - no-deps
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Make script executable
        run: chmod +x ./install-playwright.sh
      - name: Install Playwright - ${{ matrix.method }} ${{ matrix.deps }}
        env:
          METHOD: --${{ matrix.method }}
          DEPS_FLAG: ${{ matrix.deps == 'no-deps' && '--no-deps' || '' }}
        run: |
          ./install-playwright.sh $METHOD $DEPS_FLAG
      - name: List Installation Results
        run: |
          cd t
          ls -la
          cat package.json
          [[ -f "playwright.config.ts" ]] && cat playwright.config.ts
          [[ -f "tsconfig.json" ]] && cat tsconfig.json
