name: Build & Test
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: 01 13 * * SAT
jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        script:
          - install-playwright-npm-deps.sh
          - install-playwright-npm-no-deps.sh
          - install-playwright-npm-ct-deps.sh
          - install-playwright-npm-ct-no-deps.sh
          - install-playwright-pnpm-deps.sh
          - install-playwright-pnpm-no-deps.sh
          - install-playwright-pnpm-ct-deps.sh
          - install-playwright-pnpm-ct-no-deps.sh
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 20
      - name: Run Installation
        run: ./${{ matrix.script }}
      - name: List Installation Results
        run: |
          set -x
          cd t
          ls -la
          cat package.json
          [[ -f "playwright.config.ts" ]] && cat playwright.config.ts || true
          [[ -f "tsconfig.json" ]] && cat tsconfig.json || true
